name: iOS Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install pods
        run: cd ios && pod install --repo-update

      - name: Build iOS app
        run: flutter build ios --release --no-codesign
